# Generated by Django 3.2.20 on 2025-06-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='exclusive',
            field=models.BooleanField(default=False, help_text='If True, all students must see and follow this organization.'),
        ),
    ]
