# Generated by Django 3.2.20 on 2025-06-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_exclusive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url',
            field=models.CharField(blank=True, help_text="URL to the user's profile picture in Firebase Storage.", max_length=500, null=True),
        ),
    ]
