# Generated by Django 3.2.20 on 2025-06-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url',
            field=models.URLField(blank=True, help_text="URL to the user's profile picture in Firebase Storage.", max_length=500, null=True),
        ),
    ]
