# Generated by Django 3.2.20 on 2024-12-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241212_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(max_length=100),
        ),
    ]
