# Generated by Django 3.2.20 on 2025-01-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='organization',
            name='display_name_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='display_name_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
