# Generated by Django 3.2.20 on 2025-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic_url',
            field=models.URLField(blank=True, help_text="URL to the user's profile picture in Firebase Storage.", max_length=500, null=True),
        ),
    ]
