# Generated by Django 5.2.4 on 2026-01-10 21:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('creator_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WallMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=255)),
                ('interests', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='wall_photos/')),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='knowme.wall')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
    ]
