# Generated by Django 5.2.4 on 2026-02-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowme', '0002_remove_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
