# Generated by Django 3.2.20 on 2025-06-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('followee_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followee_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followee_type', to='contenttypes.contenttype')),
                ('follower_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_type', to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('follower_content_type', 'follower_object_id', 'followee_content_type', 'followee_object_id')},
            },
        ),
    ]
