# Generated by Django 5.2.4 on 2025-10-16 09:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postMang', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firestore_post_id', models.CharField(db_index=True, max_length=100, verbose_name='Firestore Post ID')),
                ('points', models.PositiveSmallIntegerField(help_text='Points given (1 to 5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_rewards', to=settings.AUTH_USER_MODEL)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Post Author')),
            ],
            options={
                'verbose_name': 'Reward Point Transaction',
                'constraints': [models.UniqueConstraint(fields=('giver', 'firestore_post_id'), name='unique_reward_per_post')],
            },
        ),
    ]
