# Generated by Django 3.2.20 on 2025-01-22 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_student_date_of_birth'),
        ('postMang', '0002_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.student'),
        ),
    ]
