# Generated by Django 3.2.20 on 2025-06-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('postMang', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='share',
            name='post',
        ),
        migrations.RemoveField(
            model_name='share',
            name='user',
        ),
        migrations.AddField(
            model_name='follow',
            name='followee_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followee_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='follow',
            name='followee_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower_content_type', 'follower_object_id', 'followee_content_type', 'followee_object_id')},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='student',
        ),
    ]
