# Generated by Django 5.2.4 on 2025-08-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, help_text='Unique device identifier (e.g., UUID for mobile app)', max_length=512, null=True, unique=True),
        ),
    ]
